import os.path
from os import listdir
from os.path import isfile, join

CHARACTER_PATH = "images/characters/"


class Character:
    def __init__(self, img_file: str, names: [str]):
        self.img_file = img_file
        self.names = names


CHARACTERS = [
    Character("apollonia.png", ["Apollonia", "Apollonia James", "Appollonia", "Apolonia", "Appolonia"]),
    Character("Ardy.png", ["Ardy"]),
    Character("ator.png", ["Ator"]),
    Character("bart_fargo.png", ["Bart Fargo", "Bart", "Fargo"]),
    Character("barugon.png", ["Barugon"]),
    Character("Batwoman.png", ["Batwoman", "Bat Woman"]),
    Character("Batwoman2.png", ["Batwoman", "Bat Woman"]),
    Character("beeper.png", ["Beeper"]),
    Character("betty.png", ["Betty", "Betty Morgan"]),
    Character("big_jake.png", ["Big Jake", "Jake"]),
    Character("billy.png", ["Billy", "Billy Duncan"]),
    Character("bix.png", ["Bix Dugan", "Big Stupid", "Bix"]),
    Character("Bobo.png", ["Bobo", "Professor Bobo", "mst3kBbo"]),
    Character("boong.png", ["Boong", "President Boong", "Pres Boong", "Prez Boong"]),
    Character("briteis.png", ["Col Briteis", "Briteis", "Brighteyes", "Bright Eyes", "Col Brighteyes", "Col Bright Eyes", "Brite Eyes", "Col Brite Eyes"]),
    Character("cabal.png", ["Cabal"]),
    Character("cabot.png", ["Cabot"]),
    Character("Cambot.png", ["Cambot"]),
    Character("captjoe.png", ["Captain Joe", "Capt Joe", "Cap Joe"]),
    Character("carrie.png", ["Carrie", "Carrie Anders"]),
    Character("cherokee_jack.png", ["Cherokee Jack"]),
    Character("Cleolanta.png", ["Cleolanta", "Cleolanthe"]),
    Character("cody.png", ["Commando Cody", "Cody"]),
    Character("coily.png", ["Coily", "Coilie"]),
    Character("cornjob.png", ["Cornjob", "Corn Job", "Kon-Chan", "Konchan", "Kondo", "Officer Kondo"]),
    Character("crenshaw.png", ["Crenshaw", "Old Man Crenshaw"]),
    Character("critter.png", ["Critter", "Finley Jones", "Critter Jones", "Finley Critter Jones"]),
    Character("crow.png", ["Crow", "Crow T Robot", "Art", "mst3kCroooow", "mst3kRahr", "mst3kSilhouetteCrow", "mst3kRock"]),
    Character("dablone.png", ["Dablone", "Toblerone"]),
    Character("daddy-o.png", ["Daddy-O", "DaddyO", "Phil", "Phil Sandifer"]),
    Character("dave.png", ["Dave", "Dave Randall"]),
    Character("dave_walker.png", ["Dave", "Dave Walker"]),
    Character("david_ryder.png", ["Dave Ryder", "David Ryder", "Ryder", "mst3kAhhh"]),
    Character("deathstalker.png", ["Deathstalker", "Death Stalker"]),
    Character("debbie.png", ["Debbie"]),
    Character("derek.png", ["Derek"]),
    Character("diabolik.png", ["Diabolik"]),
    Character("dirk.png", ["Dirk", "Dirk Williams"]),
    Character("DoctorKabahl.png", ["Dr Kabahl", "Kabahl", "Dr Kabal", "Kabal"]),
    Character("donna.png", ["Donna", "Donna Bixby"]),
    Character("dorkin.png", ["Dorkin"]),
    Character("drake.png", ["Drake", "Marion Drake"]),
    Character("drmordrid.png", ["Dr Mordrid", "Doctor Mordrid", "Anton Mordrid", "Dr Anton Mordrid", "Mordrid"]),
    Character("dropo.png", ["Dropo", "Droppo"]),
    Character("east_eddie.png", ["East Eddie"]),
    Character("eddie.png", ["Eddie", "Eddie Nelson"]),
    Character("Eegah.png", ["Eegah"]),
    Character("EmilyConnor.png", ["Emily", "Emily Connor", "Emily Crenshaw", "mst3kEmily"]),
    Character("erhardt.png", ["Dr Erhardt", "Larry", "Erhardt", "Dr Larry Erhardt", "Dr Laurence Erhardt", "mst3kLar"]),
    Character("eulabelle.png", ["Eulabelle", "Eulabell"]),
    Character("exeter.png", ["Exeter"]),
    Character("fat_man.png", ["Fat Man", "FatMan", "Chairman", "Novicorp Chairman"]),
    Character("fingal.png", ["Fingal", "Aram Fingal", "Aram", "mst3kElec"]),
    Character("forrester.png", ["Forrester", "Dr Forrester", "Clayton Forrester", "Dr Clayton Forrester", "mst3kHurt", "mst3kFor"]),
    Character("frank_chapman.png", ["Frank Chapman", "Chapman"]),
    Character("froggy.png", ["Froggy"]),
    Character("frost.png", ["Morozko", "Father Frost", "Jack Frost", "Frost", "Frosty"]),
    Character("fumanchu.png", ["Fu Manchu", "Fumanchu", "Fu Man Chu"]),
    Character("gamera.png", ["Gamera", "mst3kGameraSpin", "mst3kGamera2"]),
    Character("gaos.png", ["Gaos", "Gyaos"]),
    Character("geronimo.png", ["Geronimo", "Thomas Jefferson Geronimo", "Thomas Jefferson Geronimo III", "Deputy Sheriff Thomas Jefferson Geronimo III"]),
    Character("glennmanning.png", ["Glenn Manning", "Glen Manning", "Glenn", "Glen"]),
    Character("gloria.png", ["Gloria", "Gloria Henderson"]),
    Character("godo.png", ["Godo"]),
    Character("godzilla.png", ["Godzilla", "Gojira"]),
    Character("Gooch.png", ["Gooch", "Cooch"]),
    Character("goosio.png", ["Goosio", "mst3kGoosio"]),
    Character("gorgo.png", ["Gorgo"]),
    Character("gpc2.png", ["GPC 2", "GPC2", "GPC", "mst3kGPC"]),
    Character("Growler.png", ["Growler"]),
    Character("guiron.png", ["Guiron"]),
    Character("gumby.png", ["Gumby"]),
    Character("gypsy.png", ["Gypsy", "GPC", "mst3kGypsy", "mst3kGPC"]),
    Character("hal_moffat.png", ["Hal Moffat", "The Creeper", "Hal", "Creeper"]),
    Character("hamlet.png", ["Hamlet"]),
    Character("hercules.png", ["Hercules"]),
    Character("hobgoblins.png", ["Hobgoblins", "Hobgoblin", "Frankie", "Franky", "Sniffles", "Bounce-Bounce", "BounceBounce", "Claw", "The Claw"]),
    Character("hugo.png", ["Hugo", "Devil Doll"]),
    Character("jack_perkins.png", ["Jack Perkins", "Perkins", "mst3kPerk"]),
    Character("james_arthur_cummings.png", ["Cummings", "James Arthur Cummings", "James Cummings"]),
    Character("jan.png", ["Jan in the Pan", "Jan"]),
    Character("jc.png", ["JC", "J C"]),
    Character("jet_jaguar.png", ["Jet Jaguar", "Jetjaguar"]),
    Character("jiger.png", ["Jiger"]),
    Character("Joel.png", ["Joel", "Joel Robinson", "mst3kJoel", "mst3kItStinks"]),
    Character("joey_the_lemur.png", ["Joey the Lemur", "Joey"]),
    Character("johnny_longbow.png", ["Johnny Longbow", "Johnny Long Bow", "Johnny Longbone", "Johnny Long Bone"]),
    Character("JonahHeston.png", ["Jonah", "Jonah Heston", "mst3kJonah"]),
    Character("judy.png", ["Judy"]),
    Character("kalgan.png", ["Kalgan"]),
    Character("kemp.png", ["Kemp", "Bill Kemp"]),
    Character("ken.png", ["Ken"]),
    Character("kinga.png", ["Kinga", "Kinga Forrester", "mst3kKinga"]),
    Character("kolos.png", ["Kolos", "Dr Kolos"]),
    Character("kobras.png", ["Kobras", "Kobra", "Cobras", "Cobra"]),
    Character("krankor.png", ["Phantom of Krankor", "Krankor", "mst3kHeh"]),
    Character("lara.png", ["Lara"]),
    Character("Leonard_Maltin.png", ["Leonard Maltin", "Leonard", "Maltin"]),
    Character("Leonardo.png", ["Leonardo", "Leonardo da Vinci", "Leonardo daVinci"]),
    Character("linda.png", ["Linda"]),
    Character("lisa.png", ["Lisa", "Lisa Dornheimer"]),
    Character("lisaloeb.png", ["Lisa Loeb", "Lisa", "Loeb", "Courtney Hole"]),
    Character("liz_walker.png", ["Liz", "Liz Walker"]),
    Character("lobo.png", ["Lobo", "Lobo II", "Lobo 2", "mst3kTor"]),
    Character("lodac.png", ["Lodac"]),
    Character("logan.png", ["Logan"]),
    Character("lombardi.png", ["Lombardi", "Dr Carlo Lombardi", "Carlo Lombardi"]),
    Character("Lt_Red_Bradley.png", ["Bradley", "Red Bradley", "Red", "Lt Bradley", "Lt Red Bradley"]),
    Character("mac.png", ["Mac"]),
    Character("manuel.png", ["Manuel"]),
    Character("Margaret.png", ["Margaret", "Maggie", "mst3kScream"]),
    Character("marv.png", ["Marv", "Marv Grant"]),
    Character("master.png", ["The Master", "mst3kMaster"]),
    Character("max.png", ["Max", "TV's Max", "TV's Son of TV's Frank"]),
    Character("Max_Keller.png", ["Max Keller", "Max", "Keller"]),
    Character("MegaSynthia.png", ["Mega Synthia", "MegaSynthia"]),
    Character("megaweapon.png", ["Megaweapon", "Mega Weapon"]),
    Character("Merlin.png", ["Merlin"]),
    Character("MichaelManos.png", ["Michael", "Mike"]),
    Character("mickey.png", ["Mickey"]),
    Character("Mike.png", ["Mike", "Mike Nelson", "mst3kMike", "mst3kRobichet"]),
    Character("mikey.png", ["Mikey"]),
    Character("Minsky.png", ["Minsky"]),
    Character("mitchell.png", ["Mitchell"]),
    Character("monad.png", ["Monad"]),
    Character("mooney.png", ["Mooney", "Moon", "Bob Mooney"]),
    Character("mothra.png", ["Mothra"]),
    Character("mrb.png", ["Mr B Natural", "Mr B", "mst3kMrB"]),
    Character("munchie.png", ["Munchie"]),
    Character("MWaverly.png", ["M Waverly", "MWaverly"]),
    Character("Nanites.png", ["Nanites"]),
    Character("Natalie.png", ["Natalie", "Natalie Burke", "mst3kWerewolf"]),
    Character("nereus.png", ["Nereus"]),
    Character("nickmoon.png", ["Nick Moon", "Nick", "Moon"]),
    Character("nuveena.png", ["Nuveena"]),
    Character("observer.png", ["Observer", "Brain Guy", "Brainguy", "mst3kBrn"]),
    Character("omus.png", ["Omus"]),
    Character("ortega.png", ["Ortega", "mst3kOrtega"]),
    Character("Peaches.png", ["Peaches", "Peaches Page"]),
    Character("Pearl.png", ["Pearl", "Pearl Forrester", "mst3kPrl"]),
    Character("pepe.png", ["Pepe"]),
    Character("phipps.png", ["Alexander Phipps", "Alex", "Alexander", "Alex Phipps", "Phipps"]),
    Character("pipper.png", ["Pipper", "Mike Pipper"]),
    Character("pitch.png", ["Pitch", "mst3kPitch"]),
    Character("Princeofspace.png", ["Prince of Space"]),
    Character("pumaman.png", ["Puma Man", "Pumaman", "mst3kMoron"]),
    Character("Ro-Man.png", ["Ro-Man", "RoMan"]),
    Character("Roadrash.png", ["Roadrash", "Road Rash"]),
    Character("rodney.png", ["Rodney"]),
    Character("rocky_jones.png", ["Rocky Jones"]),
    Character("rommel.png", ["Rommel"]),
    Character("salvatore_mistretta.png", ["Mistretta", "Salvatore Mistretta"]),
    Character("sam_the_keeper.png", ["Sam", "Sam the Keeper"]),
    Character("santa_claus.png", ["Santa Claus", "Santa"]),
    Character("santo.png", ["Santo", "El Santo", "mst3kSanto"]),
    Character("Scooter.png", ["Scooter"]),
    Character("smolkin.png", ["Smolkin", "Digger Smolkin"]),
    Character("Sorri_Andropoli.png", ["Sorri", "Sorri Andropoli"]),
    Character("space_chief.png", ["Space Chief"]),
    Character("sparks.png", ["Sparks"]),
    Character("steffi.png", ["Steffi", "Steffi the Babysitter"]),
    Character("steve.png", ["Steve", "Steve Dunlap"]),
    Character("stumpy.png", ["Stumpy"]),
    Character("sumuru.png", ["Sumuru"]),
    Character("susan.png", ["Susan", "Susan Williams"]),
    Character("sybil.png", ["Sybil"]),
    Character("Synthia.png", ["Synthia"]),
    Character("syrene.png", ["Syrene"]),
    Character("tang.png", ["Tang"]),
    Character("thena.png", ["Thena"]),
    Character("thong.png", ["Thong", "Dong", "Wong"]),
    Character("tibby.png", ["Tibby"]),
    Character("tim.png", ["Tim", "Tim Thorton"]),
    Character("timmy.png", ["Timmy", "mst3kSilhouetteCrow"]),
    Character("timmy_bobby_rusty.png", ["Timmy Bobby Rusty"]),
    Character("Tom_Servo.png", ["Servo", "Tom Servo", "Htom Sirveaux", "mst3kTomServo", "mst3kSilhouetteTom"]),
    Character("tom_stewart.png", ["Tom Stewart", "Tom"]),
    Character("tony_gallano.png", ["Gallano", "Tony Gallano"]),
    Character("torgo.png", ["Torgo", "mst3kTorgo", "mst3kMTo", "mst3kHitorgo"]),
    Character("trash.png", ["Trash"]),
    Character("troy.png", ["Troy", "Troy McGreggor", "mst3kTroy"]),
    Character("trumpy.png", ["Trumpy"]),
    Character("TVs_Frank.png", ["Frank", "TV's Frank", "mst3kDeep", "mst3kFrank"]),
    Character("Vadinho.png", ["Vadinho"]),
    Character("valaria.png", ["Valaria"]),
    Character("vance.png", ["Vance", "Dr Vance"]),
    Character("Vena.png", ["Vena", "Vena Ray"]),
    Character("vi.png", ["Vi", "movievVi", "mst3kTorm"]),
    Character("vic_mathias.png", ["Vic Mathias", "Vic", "Mathias"]),
    Character("Vorelli.png", ["Vorelli", "The Great Vorelli"]),
    Character("wanama.png", ["Wanama"]),
    Character("watney.png", ["Watney", "Whatney"]),
    Character("winky.png", ["Winky"]),
    Character("xenos.png", ["Xenos"]),
    Character("XT-5000.png", ["XT-5000", "XT 5000", "XT-5K", "XT 5K"]),
    Character("yogi.png", ["Yogi"]),
    Character("Yuri.png", ["Yuri"]),
    Character("ZapRowsdower.png", ["Rowsdower", "Zap", "Zap Rowsdower", "mst3kBeer", "mst3kRows"]),
    Character("zigra.png", ["Zigra"]),
    Character("zorka.png", ["Dr Zorka", "Doctor Zorka", "Dr Alex Zorka", "Zorka", "Alex Zorka"])
]


if __name__ == '__main__':
    # Verify the file names are correct.
    for c in CHARACTERS:
        if not os.path.exists(CHARACTER_PATH + c.img_file):
            print(c.img_file + " is missing")

    allfiles = [f for f in listdir(CHARACTER_PATH) if isfile(join(CHARACTER_PATH, f))]
    for file in allfiles:
        found = False
        for c in CHARACTERS:
            if c.img_file == file:
                found = True
                break
        if not found:
            print("File " + file + " has no Character")

"""
TODO:

"""
