# First entry in the movie name list should be the full, real movie name

MOVIE_NAMES = {
    "205": ["Rocket Attack U.S.A.", "Rocket Attack"],
    "206": ["Ring of Terror"],
    "207": ["Wild Rebels"],
    "208": ["Lost Continent"],
    "209": ["The Hellcats"],
    "210": ["King Dinosaur"],
    "211": ["First Spaceship on Venus", "The First Spaceship to Venus", "First Spaceship"],
    "212": ["Godzilla vs Megalon"],
    "213": ["Godzilla vs the Sea Monster"],
    "301": ["Cave Dwellers", "The Blade Master"],
    "302": ["Gamera"],
    "303": ["Pod People"],
    "304": ["Gamera vs Barugon"],
    "305": ["Stranded in Space"],
    "306": ["Time of the Apes"],
    "307": ["Daddy-O", "Daddy O"],
    "308": ["Gamera vs Gaos"],
    "309": ["The Amazing Colossal Man", "Colossal Man"],
    "310": ["Fugitive Alien", "Fugitive Alien I", "Fugitive Alien 1"],
    "311": ["It Conquered the World"],
    "312": ["Gamera vs Guiron"],
    "313": ["Earth vs the Spider"],
    "314": ["Mighty Jack"],
    "315": ["Teenage Cave Man", "Teenage Caveman", "Teen Age Caveman", "Teen Age Cave Man"],
    "316": ["Gamera vs Zigra"],
    "317": ["The Saga of the Viking Women and Their Voyage to the Waters of the Great Sea Serpent",
            "Viking Women and the Sea Serpent", "Viking Women"],
    "318": ["Star Force: Fugitive Alien II", "Star Force: Fugitive Alien 2", "Fugitive Alien II",
            "Fugitive Alien 2", "Star Force"],
    "319": ["War of the Colossal Beast", "Colossal Beast"],
    "320": ["The Unearthly"],
    "321": ["Santa Claus Conquers the Martians", "Santa Claus vs the Martians", "Santa Conquers the Martians",
            "Santa vs the Martians"],
    "322": ["Master Ninja I", "Master Ninja 1", "Master Ninja"],
    "323": ["The Castle of Fu Manchu", "Fu Manchu", "FuManchu"],
    "324": ["Master Ninja II", "Master Ninja 2"],
    "401": ["Space Travelers", "Marooned"],
    "402": ["The Giant Gila Monster", "Gila Monster"],
    "403": ["City Limits"],
    "404": ["Teenagers from Outer Space"],
    "405": ["Being from Another Planet", "Time Walker", "Timewalker"],
    "406": ["Attack of the Giant Leeches", "Giant Leeches"],
    "407": ["The Killer Shrews"],
    "408": ["Hercules Unchained", "Herc Unchained"],
    "409": ["Indestructible Man"],
    "410": ["Hercules Against the Moon Men", "Hercules vs the Moon Men"],
    "411": ["The Magic Sword"],
    "412": ["Hercules and the Captive Women", "Herc and the Captive Women", "Captive Women"],
    "413": ["Manhunt in Space", "Man Hunt in Space"],
    "414": ["Tormented"],
    "415": ["The Beatniks"],
    "416": ["Fire Maidens of Outer Space", "Fire Maidens from Outer Space", "Fire Maidens"],
    "417": ["Crash of Moons"],
    "418": ["Attack of the the Eye Creatures", "Eye Creatures"],
    "419": ["The Rebel Set"],
    "420": ["The Human Duplicators"],
    "421": ["Monster A-Go Go", "Monster A-GoGo", "Monster A Go Go"],
    "422": ["The Day the Earth Froze", "Sampo"],
    "423": ["Bride of the Monster"],
    "424": ["Manos: The Hands of Fate", "Manos", "The Hands of Fate"],
    "501": ["Warrior of the Lost World"],
    "502": ["Hercules"],
    "503": ["Swamp Diamonds"],
    "504": ["Secret Agent Super Dragon", "Super Dragon"],
    "505": ["The Magic Voyage of Sinbad", "Sinbad", "Magic Voyage"],
    "506": ["Eegah"],
    "507": ["I Accuse My Parents"],
    "508": ["Operation Double 007", "Operation Kid Brother", "OK Connery", "Secret Agent 00"],
    "509": ["The Girl in Lovers Lane"],
    "510": ["The Painted Hills"],
    "511": ["Gunslinger"],
    "512": ["Mitchell"],
    "513": ["The Brain That Wouldn't Die", "The Brain That Couldn't Die"],
    "514": ["Teen-Age Strangler"],
    "515": ["The Wild Wild World of Batwoman", "Wild World of Batwoman", "World of Batwoman"],
    "516": ["Alien from L.A."],
    "517": ["Beginning of the End"],
    "518": ["The Atomic Brain"],
    "519": ["Outlaw", "Outlaw of Gor", "Outlaw Gor", "Gor"],
    "520": ["Radar Secret Service"],
    "521": ["Santa Claus", "Santa"],
    "522": ["Teen-Age Crime Wave", "Teenage Crimewave", "Teen Age Crime Wave", "Teen Age Crimewave"],
    "523": ["Village of the Giants"],
    "524": ["12 to the Moon", "Twelve to the Moon"],
    "601": ["Girls Town"],
    "602": ["Invasion USA"],
    "603": ["The Dead Talk Back"],
    "604": ["Zombie Nightmare"],
    "605": ["Colossus and the Headhunters", "Colossus and the Head Hunters"],
    "606": ["The Creeping Terror"],
    "607": ["Bloodlust!", "Blood Lust"],
    "608": ["Code Name: Diamond Head", "Diamond Head"],
    "609": ["The Skydivers"],
    "610": ["The Violent Years"],
    "611": ["Last of the Wild Horses", "Wild Horses"],
    "612": ["The Starfighters", "The Star Fighters"],
    "613": ["The Sinister Urge"],
    "614": ["San Francisco International", "San Francisco Intl", "SF International", "SF Intl"],
    "615": ["Kitten with a Whip"],
    "616": ["Racket Girls"],
    "617": ["The Sword and the Dragon"],
    "618": ["High School Big Shot"],
    "619": ["Red Zone Cuba"],
    "620": ["Danger!! Death Ray"],
    "621": ["The Beast of Yucca Flats"],
    "622": ["Angels Revenge"],
    "623": ["The Amazing Transparent Man", "Transparent Man"],
    "624": ["Samson vs the Vampire Women", "Vampire Women"],
    "701": ["Night of the Blood Beast", "Blood Beast", "Bloodbeast", "701T"],
    "702": ["The Brute Man"],
    "703": ["Deathstalker and the Warriors from Hell", "Deathstalker"],
    "704": ["The Incredible Melting Man", "Melting Man"],
    "705": ["Escape 2000", "Escape from the Bronx", "Bronx Warriors 2", "Fuga dal Bronx"],
    "706": ["Laserblast", "Laser Blast"],
    "801": ["Revenge of the Creature"],
    "802": ["The Leech Woman"],
    "803": ["The Mole People"],
    "804": ["The Deadly Mantis"],
    "805": ["The Thing That Couldn't Die", "The Thing That Wouldn't Die"],
    "806": ["The Undead"],
    "807": ["Terror from the Year 5000", "Terror from 5000"],
    "808": ["The She-Creature", "The She Creature", "The Shecreature"],
    "809": ["I Was a Teenage Werewolf", "I Was a Teen Age Werewolf"],
    "810": ["The Giant Spider Invasion", "Spider Invasion"],
    "811": ["Parts: The Clonus Horror", "Parts", "Clonus", "Clonus Horror"],
    "812": ["The Incredibly Strange Creatures Who Stopped Living and Became Mixed-Up Zombies!!?",
            "TISCWSLABMUZ", "The Incredibly Strange Creatures", "Strange Creatures", "Mixed-Up Zombies"],
    "813": ["Jack Frost", "Morozko", "Frosty"],
    "814": ["Riding with Death"],
    "815": ["Agent for H.A.R.M."],
    "816": ["Prince of Space"],
    "817": ["The Horror of Party Beach", "Party Beach"],
    "818": ["Devil Doll"],
    "819": ["Invasion of the Neptune Men", "Neptune Men"],
    "820": ["Space Mutiny"],
    "821": ["Time Chasers"],
    "822": ["Overdrawn at the Memory Bank", "Overdrawn", "Memory Bank"],
    "901": ["The Projected Man"],
    "902": ["The Phantom Planet"],
    "903": ["The Pumaman", "The Puma Man"],
    "904": ["Werewolf"],
    "905": ["The Deadly Bees"],
    "906": ["The Space Children"],
    "907": ["Hobgoblins"],
    "908": ["The Touch of Satan"],
    "909": ["Gorgo"],
    "910": ["The Final Sacrifice"],
    "911": ["Devil Fish"],
    "912": ["The Screaming Skull"],
    "913": ["Quest of the Delta Knights", "Delta Knights"],
    "1001": ["Soultaker"],
    "1002": ["Girl in Gold Boots", "Gold Boots"],
    "1003": ["Merlin's Shop of Mystical Wonders", "Merlin's Shop", "Merlin's Shop of Wonders"],
    "1004": ["Future War"],
    "1005": ["Blood Waters of Dr. Z", "ZaAt", "Blood Waters", "Dr Z"],
    "1006": ["Boggy Creek II: and the Legend Continues…", "Boggy Creek", "Boggy Creek II", "Boggy Creek 2"],
    "1007": ["Track of the Moon Beast", "Moon Beast"],
    "1008": ["Final Justice"],
    "1009": ["Hamlet"],
    "1010": ["It Lives by Night"],
    "1011": ["Horrors of Spider Island", "Spider Island"],
    "1012": ["Squirm"],
    "1013": ["Diabolik"],
    "1101": ["Reptilicus"],
    "1102": ["Cry Wilderness"],
    "1103": ["The Time Travelers"],
    "1104": ["Avalanche"],
    "1105": ["The Beast of Hollow Mountain", "Hollow Mountain"],
    "1106": ["Starcrash", "Star Crash"],
    "1107": ["The Land That Time Forgot", "Land Time Forgot"],
    "1108": ["The Loves of Hercules", "Loves of Herc"],
    "1109": ["Yongary - Monster from the Deep", "Yongary", "Monster of the Deep"],
    "1110": ["Wizards of the Lost Kingdom", "Wizards of the Lost Kingdom I", "Wizards of the Lost Kingdom 1" 
             "Lost Kingdom", "Lost Kingdom I", "Lost Kingdom 1"],
    "1111": ["Wizards of the Lost Kingdom II", "Wizards of the Lost Kingdom 2", "Lost Kingdom 2",
             "Lost Kingdom II"],
    "1112": ["Carnival Magic"],
    "1113": ["The Christmas That Almost Wasn't", "Xmas That Almost Wasn't", "Il Natale Che Quasi Non Fu"],
    "1114": ["At the Earth's Core", "Earth's Core"],
    "1201": ["Mac and Me", "Mac & Me"],
    "1202": ["Atlantic Rim"],
    "1203": ["Lords of the Deep"],
    "1204": ["The Day Time Ended"],
    "1205": ["Killer Fish"],
    "1206": ["Ator, the Fighting Eagle", "Ator", "Fighting Eagle"],
    "1301": ["Santo in the Treasure of Dracula", "Santo", "Treasure of Dracula"],
    "1302": ["Robot Wars"],
    "1303": ["Beyond Atlantis"],
    "1304": ["Munchie", "Munchy"],
    "1305": ["Doctor Mordrid", "Dr Mordrid"],
    "1306": ["Demon Squad"],
    "1307": ["Gamera vs Jiger"],
    "1308": ["The Batwoman"],
    "1309": ["The Million Eyes of Sumuru", "Sumuru", "Million Eyes"],
    "1310": ["H.G. Wells' The Shape of Things to Come", "The Shape of Things to Come", "Things to Come"],
    "1311": ["The Mask"],
    "1312": ["The Bubble"],
    "1313": ["The Christmas Dragon", "Xmas Dragon"],
}
